@startuml
class Customer{
    - Long customerId
    - String firstName
    - String lastName
    - List<Transaction> orderedPlants
}

class Transaction{
    - Long transactionId
    - Plant plant
    - Customer customer
    - LocalDate dateOfTransaction
}

class Plant{
    - Long plantId
    - String plantName
    - PlantType plantType
}

class CropArea{
    - Long cropAreaId
    - List<Plant> plantList
}
Customer "1" -- "*" Transaction : buys
Plant "1" -right- "*" Transaction : is ordered
CropArea "1" -- "*" Plant : planted
@enduml
